name: Publish Docker Image

on:
  push:
    branches:
      - master

    paths-ignore:
      - '**.md'
      - '.github/workflows/*yml'

  pull-request:
    branches:
      - master

    paths-ignore:
      - '**.md'
      - '.github/workflows/*yml'

  # Enable manually run in Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Buiild and start containers
        run: docker-compose up -d --build

      - name: Run tests
        run: docker-compose exec -T app pytest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          context: .
          push: true
          tags: jnta/example-app:latest
