name: Publish Docker Image

on:
  push:
    branches:
      - master

    paths-ignore:
      - '**.md'
      - '.github/workflows/*yml'

  pull_request:
    branches:
      - master

    paths-ignore:
      - '**.md'
      - '.github/workflows/*yml'

  # Enable manually run in Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Buiild and start containers
        run: docker-compose up -d --build

      - name: Run tests
        run: docker-compose exec -T app pytest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push backend app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jnta/example-app:latest
